serviceMetadata:
  tribe: '' # eg 'satu-data'
  squad: '' # eg 'rapor-pendidkan'
  env: 'staging'

# BASIC
applicationName: '' # eg. rapor-pendidikan-fe
env: staging

# SERVICE ACCOUNT & GKE Workload Indentity
serviceAccount:
  name: default
  create: false

# PICs
deploymentAnnotations:
  pic: ''
  slack: ''

# BERGLAS
berglas:
  enabled: false

# IMAGE
containerImage:
  # 💣 UPDATE THIS
  repository: # eg. asia.gcr.io/belajar-id-networks/wartek-id/data-pipeline/rapor-pendidikan-frontend/staging
  tag: latest
  pullPolicy: IfNotPresent

# ENV CONFIGS
envVars: {}

# SCALING
replicaCount: 2
containerResources:
  limits:
    cpu: 500m
    memory: 600Mi
  requests:
    cpu: 500m
    memory: 600Mi
horizontalPodAutoscaler:
  # TODO: configure proper HPA before launch
  enabled: false
  minReplicas: 2
  maxReplicas: 10

# PROBES
# TODO: configure proper liveness and readiness probe before launch
livenessProbe:
  httpGet:
    path: /app/api/healthz
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 30
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  httpGet:
    path: /app/api/healthz
    port: 3000
  initialDelaySeconds: 0
  periodSeconds: 5
  timeoutSeconds: 30
  failureThreshold: 3
  successThreshold: 1

# PORTS
containerPorts:
  http:
    port: 3000
    protocol: TCP

# SERVICE
service:
  enabled: true
  annotations:
    cloud.google.com/neg: '{"exposed_ports": { "3000":{}}}'
  ports:
    http:
      port: 3000
      targetPort: 3000
      protocol: TCP

# AMBASSADOR
ambassador:
  enabled: false
